name: Docs

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/docs.yml"
      - "src/**"
      - "README.md"
  pull_request:
    branches: [ "master" ]
    paths:
      - ".github/workflows/docs.yml"
      - "src/**"
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build docs &&
      run: |
        cargo doc
        # Point site to correct index.html
        echo "<meta http-equiv=\"refresh\" content=\"0; url=skala_engine_numerics\">" > index.html
    
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/
        keep_files: false
